CREATE TABLE `dynaflow`.`items_master` (
  `id` BIGINT NOT NULL,
  `part_id` VARCHAR(100) NULL,
  `price` FLOAT NULL,
  `duty` FLOAT NULL,
  `discount` FLOAT NULL,
  `family_code` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;



PART NUMBER
DESCRIPTION
ADDITIONAL INFORMATION 1
ADDITIONAL INFORMATION 2
ADDITIONAL INFORMATION 3
DUTIES (%)
SELLING PRICE (RM)
LEAD TIME (ARO)
DYNAFLO DISCOUNT CODE
OLD PART NUMBER
LATEST DATE PURCHASED
SUPPLIER
ITEM REFERENCE
EQUIPMENT/PACKAGE REFERENCE
GRACO REFERENCE
GRACO FAMILY TYPE 
GRACO FAMILY DISCOUNT 
GRACO STD. DISCOUNT CODE 
GRACO STD. DISCOUNT
SUPPLIER  CODE





		
